apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bases
  - ingress.yaml
  - issuer.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: broker
      app.kubernetes.io/created-by: harmelodic
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: broker
      app.kubernetes.io/part-of: pact
      app.kubernetes.io/version: latest
