apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: harmelodic
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: argo-cd-ingress
      app.kubernetes.io/part-of: argo-cd-ingress
      app.kubernetes.io/version: latest
resources:
  - ../bases
  - ingress.yaml
  - issuer.yaml
