apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: cert-manager
      app.kubernetes.io/created-by: harmelodic
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/part-of: cert-manager
      app.kubernetes.io/version: latest
resources:
  - cert-manager.yaml
  - namespace.yaml
