apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pact-broker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Harmelodic/personal-apps.git
    targetRevision: HEAD
    path: manifests/pact-broker/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: pact
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
