apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-public
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.14.3
    helm:
      releaseName: public
      valuesObject:
        controller:
          electionID: public-ingress-controller-leader # Needed for when installing multiple ingress-nginx in the same namespace
          ingressClassResource:
            name: public
          replicaCount: 2
          resources:
            requests:
              cpu: 3m
              memory: 90Mi
            limits:
              memory: 90Mi
        revisionHistoryLimit: 0
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
