apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: ingress-nginx
      app.kubernetes.io/created-by: harmelodic
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
      app.kubernetes.io/version: latest
resources:
  - namespace.yaml
  - ingress-nginx-public.yaml
